# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'traning_Udemy_sec22' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for traning_Udemy_sec22
		
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'lottie-ios'
	pod 'ChameleonFramework'

end
